
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ASUS
 */
public class BERANDADUA extends javax.swing.JFrame {

    /**
     * Creates new form BERANDADUA
     */
    public BERANDADUA() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        panel = new javax.swing.JTabbedPane();
        pertanyaan = new javax.swing.JPanel();
        Tombol = new javax.swing.JPanel();
        Submit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Tanggal = new javax.swing.JTextField();
        Bulan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tabhasil = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        keluardaridunia = new javax.swing.JButton();
        hasil = new javax.swing.JButton();
        balik = new javax.swing.JButton();
        aquarius = new javax.swing.JLabel();
        aries = new javax.swing.JLabel();
        taurus = new javax.swing.JLabel();
        cancer = new javax.swing.JLabel();
        gemini = new javax.swing.JLabel();
        leo = new javax.swing.JLabel();
        libra = new javax.swing.JLabel();
        pisces = new javax.swing.JLabel();
        sagitarius = new javax.swing.JLabel();
        scorpio = new javax.swing.JLabel();
        capricorn = new javax.swing.JLabel();
        virgo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        yoyo = new javax.swing.JTextArea();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1369, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(102, 0, 102));

        pertanyaan.setBackground(new java.awt.Color(255, 204, 204));
        pertanyaan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tombol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TombolMousePressed(evt);
            }
        });
        Tombol.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Submit.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        Submit.setText("SUBMIT");
        Tombol.add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        pertanyaan.add(Tombol, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 550, 120, 40));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        jLabel1.setText("MASUKKAN TANGGAL DAN BULAN");
        pertanyaan.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, 40));
        pertanyaan.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(713, 134, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        jLabel3.setText("LAHIR ANDA");
        pertanyaan.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        jLabel4.setText("TANGGAL  :");
        pertanyaan.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        jLabel5.setText("BULAN     :");
        pertanyaan.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 490, 180, 40));

        Tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanggalActionPerformed(evt);
            }
        });
        pertanyaan.add(Tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, 100, 40));

        Bulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BulanActionPerformed(evt);
            }
        });
        Bulan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BulanKeyTyped(evt);
            }
        });
        pertanyaan.add(Bulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 490, 100, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pilar kirii_1.png"))); // NOI18N
        pertanyaan.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, -90, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pilar kirii.png"))); // NOI18N
        pertanyaan.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, -90, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beranda.png"))); // NOI18N
        pertanyaan.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, -1, -1));

        panel.addTab("tab1", pertanyaan);

        tabhasil.setBackground(new java.awt.Color(255, 204, 204));
        tabhasil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel9.setText("TERIMAKASIH TELAH BERKUNJUNG");
        tabhasil.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 590, -1, -1));

        keluardaridunia.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        keluardaridunia.setText("CLICK EXIT HERE ");
        keluardaridunia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluardariduniaActionPerformed(evt);
            }
        });
        tabhasil.add(keluardaridunia, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 550, 270, -1));

        hasil.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        hasil.setText("ZODIAK ANDA ADALAH");
        hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilActionPerformed(evt);
            }
        });
        tabhasil.add(hasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, 60));

        balik.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        balik.setText("BACK");
        balik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balikActionPerformed(evt);
            }
        });
        tabhasil.add(balik, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 550, 110, 40));

        aquarius.setIcon(new javax.swing.ImageIcon(getClass().getResource("/akua.png"))); // NOI18N
        tabhasil.add(aquarius, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, -1, -1));

        aries.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aries.png"))); // NOI18N
        tabhasil.add(aries, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, -1));

        taurus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/taurus.png"))); // NOI18N
        tabhasil.add(taurus, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, -1, -1));

        cancer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancerr.png"))); // NOI18N
        tabhasil.add(cancer, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, -1));

        gemini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gemini.png"))); // NOI18N
        tabhasil.add(gemini, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, -1, -1));

        leo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/leo.png"))); // NOI18N
        tabhasil.add(leo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, -1, -1));

        libra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libra.png"))); // NOI18N
        tabhasil.add(libra, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, -1, -1));

        pisces.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pisces.png"))); // NOI18N
        tabhasil.add(pisces, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, -1, -1));

        sagitarius.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sagi.png"))); // NOI18N
        tabhasil.add(sagitarius, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, -1, -1));

        scorpio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scorpio.png"))); // NOI18N
        tabhasil.add(scorpio, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, -1, -1));

        capricorn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/capri.png"))); // NOI18N
        tabhasil.add(capricorn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        virgo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agak.png"))); // NOI18N
        tabhasil.add(virgo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        yoyo.setEditable(false);
        yoyo.setColumns(20);
        yoyo.setFont(new java.awt.Font("Script MT Bold", 1, 13)); // NOI18N
        yoyo.setRows(5);
        yoyo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                yoyoMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(yoyo);

        tabhasil.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 510, 100));

        panel.addTab("tab2", tabhasil);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 2174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 1147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TanggalActionPerformed

    private void BulanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BulanKeyTyped

        // TODO add your handling code here:
    }//GEN-LAST:event_BulanKeyTyped

    private void BulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BulanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BulanActionPerformed

    private void TombolMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TombolMousePressed
        // TODO add your handling code here:
        int x = Integer.parseInt(Tanggal.getText());
        int y = Integer.parseInt(Bulan.getText());
        if ((x >= 21 && y == 3) || (x <= 19 && y == 4)) {
            String z = "ZODIAK ANDA ADALAH ARIES";
            yoyo.setText("*zodiak ini dikenal sebagai sosok yang ambisius dialmbangkan dengan seekor domba *\n* zodiak ini sangat cocok berpasangan dengan aquarius *\n*  karier seorang Aries akan sedikit murung dalam pekerjaan *\n* status keuangan anda sedang krisis*\n*");
            hasil.setText(z);
            aries.setVisible(true);
            tampil(new JLabel [] {aquarius, taurus,cancer,gemini,scorpio,libra,leo,capricorn,pisces,sagitarius,virgo});
            panel.setSelectedIndex(1);
        }
        if ((x >= 20 && y == 4) || (x <= 20 && y == 5)) {
            String z = "ZODIAK ANDA ADALAH TAURUS";
             yoyo.setText("*zodiak ini dikenal sebagai sosok yang kuat dilambangkan dengan seekor banteng *\\n* zodiak ini sangat cocok berpasangan dengan virgo *\n* karier Taurus akan sedikit sibuk *\n* membutuhkan banyaak energi untuk mengatur keuangan*\n*");
            hasil.setText(z);
            taurus.setVisible(true);
            tampil(new JLabel [] {aquarius, aries, cancer,gemini,scorpio,libra,leo,capricorn,pisces,sagitarius,virgo});
            panel.setSelectedIndex(1);
        }
        if ((x >= 21 && y == 5) || (x <= 20 && y == 6)) {
            String z = "ZODIAK ANDA ADALAH GEMINI";
             yoyo.setText("zodiak ini dikenal sebagai sosok yang banyak minat dilambangkan dengan manusia kembar *\n* zodiak ini sangat cocok berpasangand dengan libra *\n* seseorang tampak mencoba menempatkan posisimu *\n* keuangan gemini cukup baik");
            hasil.setText(z);
            gemini.setVisible(true);
            tampil(new JLabel [] {aquarius, aries, cancer,leo,libra,sagitarius,scorpio,capricorn,pisces,taurus,virgo});
            panel.setSelectedIndex(1);
        }
        if ((x >= 21 && y == 6) || (x <= 22 && y == 7)) {
            String z = "ZODIAK ANDA ADALAH CANCER";
             yoyo.setText("*zodiak ini dikenal sebagai sosok yang protektif dilambangkan dengan seekor kepiting *\n* zodiak ini sangat cocok berpasangan dengan scorpio *\n* Emosi cukup mendominasi dan mempengaruhi seorang Cancer *\n* Cancer tampak aman untuk di minggu ini");
            hasil.setText(z);
            cancer.setVisible(true);
            tampil(new JLabel [] {aquarius, aries,leo,libra,sagitarius,scorpio,capricorn,gemini,pisces,taurus,virgo});
            panel.setSelectedIndex(1);
        }
        if ((x >= 23 && y == 7) || (x <= 22 && y == 8)) {
            String z = "ZODIAK ANDA ADALAH LEO";
            yoyo.setText("*zodiak ini dikenal sebagai sosok yang percaya diri dialmbangkan dengan seekor singa */n* zodiak ini sangat cocok berpasangan dengan sagitarius */n*  seorang teman akan mengajak berbicara terkait anggaranHal ini mempengaruhimu dalam mencari kesempatan kerja */n*  Cobalah untuk berdiskusi dengan baik di minggu ini");
            //String r = "test";
           hasil.setText(z);
            leo.setVisible(true);
            tampil(new JLabel [] {aquarius, aries,gemini,pisces,taurus,libra,sagitarius,scorpio,capricorn,cancer,virgo});
            panel.setSelectedIndex(1);
        }
        if ((x >= 23 && y == 8) || (x <= 22 && y == 9)) {
            String z = "ZODIAK ANDA ADALAH VIRGO";
            yoyo.setText("* Zodiak ini dikenal sebagai sosok yang lembut dilambangkan \n dengan seorang dewi * \n * Zodiak ini sangat cocok berpasangan dengan capricorn,taurus dan scorpio *  \n * Jaga kesehatan mental anda* \n *Status keuangan anda stabil * ");
            hasil.setText(z);
            virgo.setVisible(true);
            tampil(new JLabel [] {aquarius, aries,leo,libra,taurus,sagitarius,scorpio,capricorn,cancer,gemini,pisces});
            panel.setSelectedIndex(1);
       
        }
        if ((x >= 23 && y == 9) || (x <= 22 && y == 10)) {
            String z = "ZODIAK ANDA ADALAH LIBRA";
            yoyo.setText("* zodiak ini dikenal sebagai sosok yang penuh kedamaian dilambangkan dengan timbangan *\n* zodiak ini sangat cocok berpasangan dengan gemini *\n* Lakukan pekerjaan dengan cepat dan efisien.  *\n*  keuangan Libra tampak berjalan dengan lancar.");
            hasil.setText(z);
            libra.setVisible(true);
            tampil(new JLabel [] {aquarius, aries,leo,taurus,sagitarius,scorpio,capricorn,cancer,gemini,pisces,virgo});
            panel.setSelectedIndex(1); 
        }
        if ((x >= 23 && y == 10) || (x <= 22 && y == 11)) {
            String z = "ZODIAK ANDA ADALAH SCORPIO";
            yoyo.setText("* zodiak ini dikenal sebagai sosok yang keras kepalaa dilambangkan dengan kalajengking *\n* zodiak ini sangat cocok berpasangan dengan pisces *\n* Waktu yang baik untuk bekerja lebih giat lagi dalam menunjukkan performa  *\n*  Cobalah untuk melihat dan jalan ke depan tanpa keraguan ya.");
           hasil.setText(z);
            scorpio.setVisible(true);
            tampil(new JLabel [] {aquarius, aries,leo,libra,sagitarius,cancer,capricorn, taurus,gemini,pisces,virgo});
            panel.setSelectedIndex(1);
        }
        if ((x >= 23 && y == 11) || (x <= 21 && y == 12)) {
            String z = "ZODIAK ANDA ADALAH SAGITARIUS";
            yoyo.setText("* zodiak ini dikenal sebagai sosok yang ekstrovert dilambangkan dengan cetaurus *\n* zodiak ini sangat cocok berpasangan dengan aries *\n* akan membawa keberhasilan dari hal-hal kecil*\n* Kondisi keuangan Sagitarius tampak membaik");
            hasil.setText(z);
            sagitarius.setVisible(true);
            tampil(new JLabel [] {aquarius, aries,leo,libra,cancer,scorpio,capricorn,taurus,gemini,pisces,virgo});
            panel.setSelectedIndex(1);
        }
        if ((x >= 22 && y == 12) || (x <= 19 && y == 1)) {
            String z = "ZODIAK ANDA ADALAH CAPRICORN";
             yoyo.setText("*zodiak ini dikenal sebagai sosok yang bijaksana dilambangkan dengan seekor kambing *\n* zodiak ini sangat cocok berpasangan dengan taurus *\n* akan menangani banyal hal tentang masalah hidup. Perhatikan langkahmu *\n* akan ada pengeluaran yang melebihi anggaran.");
            hasil.setText(z);
            capricorn.setVisible(true);
            tampil(new JLabel [] {aquarius, aries,leo,libra,sagitarius,scorpio,taurus,cancer,gemini,pisces,virgo});
            panel.setSelectedIndex(1);
        }
        if ((x >= 20 && y == 1) || (x <= 18 && y == 2)) {
            String z = "ZODIAK ANDA ADALAH AQUARIUS";
            yoyo.setText("*zodiak ini dikenal sebagai sosok yang tenang dilambangkan dengan air mengalir *\n* zodiak ini sangat cocok berpasangan dengan gemini *\n* akan ditawarkan sumber daya yang tak terduga *\n*  Kamu akan menerima hadiah dari anggota keluarga yang cukup berharga.");
            hasil.setText(z);
            aquarius.setVisible(true);
            tampil(new JLabel [] {taurus, aries,cancer,leo,libra,scorpio,sagitarius,gemini,pisces,capricorn,virgo});
            panel.setSelectedIndex(1);
            
        }
        if ((x >= 19 && y == 2) || (x <= 20 && y == 3)) {
            String z = "ZODIAK ANDA ADALAH PISCES";
           yoyo.setText("*zodiak ini dikenal sebagai sosok yang romantis dilambangkan dengan dua ikan *\n* zodiak ini sangat cocok berpasangan dengan scorpio *\n* seorang Pisces akan menemukan alur kebahagiaan.*\n* Tengah memikirkan pengeluaran yang diluar anggaran untuk dikelola lebih baik lagi"); 
           hasil.setText(z);
            pisces.setVisible(true);
            tampil(new JLabel [] {aquarius, aries,leo,libra,sagitarius,scorpio,capricorn,cancer,gemini,taurus,virgo});
            panel.setSelectedIndex(1);
        }
    }//GEN-LAST:event_TombolMousePressed

    private void keluardariduniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluardariduniaActionPerformed
         System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_keluardariduniaActionPerformed

    private void hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_hasilActionPerformed

    private void balikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balikActionPerformed
        this.dispose();//unutk menutup layar yang sudah terbuka sebelumnya
        new BERANDADUA().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_balikActionPerformed

    private void yoyoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yoyoMouseEntered
//yoyo.setText("yalah");      // TODO add your handling code here:
    }//GEN-LAST:event_yoyoMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BERANDADUA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BERANDADUA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BERANDADUA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BERANDADUA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BERANDADUA().setVisible(true);
            }
        });
        
        
    }
    private void tampil(JLabel [] Indikator){
        for(int i=0; i<Indikator.length; i++){
            Indikator[i].setVisible(false);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bulan;
    private javax.swing.JLabel Submit;
    private javax.swing.JTextField Tanggal;
    private javax.swing.JPanel Tombol;
    private javax.swing.JLabel aquarius;
    private javax.swing.JLabel aries;
    private javax.swing.JButton balik;
    private javax.swing.JLabel cancer;
    private javax.swing.JLabel capricorn;
    private javax.swing.JLabel gemini;
    private javax.swing.JButton hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton keluardaridunia;
    private javax.swing.JLabel leo;
    private javax.swing.JLabel libra;
    private javax.swing.JTabbedPane panel;
    private javax.swing.JPanel pertanyaan;
    private javax.swing.JLabel pisces;
    private javax.swing.JLabel sagitarius;
    private javax.swing.JLabel scorpio;
    private javax.swing.JPanel tabhasil;
    private javax.swing.JLabel taurus;
    private javax.swing.JLabel virgo;
    private javax.swing.JTextArea yoyo;
    // End of variables declaration//GEN-END:variables
}
