
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class SPLASH extends javax.swing.JFrame {

    /**
     * Creates new form SPLASH
     */
    public SPLASH() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progres = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        yoyo = new javax.swing.JProgressBar();
        loading = new javax.swing.JLabel();
        persen = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        progres.setBackground(new java.awt.Color(255, 204, 204));
        progres.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 51));
        jLabel1.setText("MY ZODIAc!");
        progres.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 370, 110));
        progres.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, -1));

        yoyo.setForeground(new java.awt.Color(204, 153, 0));
        yoyo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yoyoMouseClicked(evt);
            }
        });
        progres.add(yoyo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 590, 670, -1));

        loading.setText("loading....");
        progres.add(loading, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 560, -1, -1));

        persen.setText("0%");
        progres.add(persen, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 560, -1, 20));

        jLabel3.setFont(new java.awt.Font("STLiti", 1, 24)); // NOI18N
        jLabel3.setText("Created by Yohana Resty Agatha");
        progres.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 610, -1, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/splash.png"))); // NOI18N
        progres.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, -1));
        progres.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(progres, javax.swing.GroupLayout.DEFAULT_SIZE, 1440, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(progres, javax.swing.GroupLayout.DEFAULT_SIZE, 901, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void yoyoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yoyoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_yoyoMouseClicked

    /**
     * @param args the command line arguments
     */
    public void satu(){
        this.dispose();
        new BERANDASIJI().setVisible(true);
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SPLASH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SPLASH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SPLASH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SPLASH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        SPLASH terserah = new SPLASH ();
        terserah.setVisible(true);
        try{
            for(int i=0; i<=100; i++){
                Thread.sleep(100);
                terserah.persen.setText(i+"%");//variabel nilai
                if(i==10) {
                    terserah.loading.setText("oke...");//nama variabel loading
                    
                }
                if(i==30) {
                    terserah.loading.setText("bentarr...");
                    
                }
                if(i==70) {
                    terserah.loading.setText("dikit lagi...");
                    
                }
                if(i==90) {
                    terserah.loading.setText("nah udah tuh...");
                    
                }
                terserah.yoyo.setValue(i);//progres itu progres bar
            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SPLASH().setVisible(true);
                terserah.satu();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel loading;
    private javax.swing.JLabel persen;
    private javax.swing.JPanel progres;
    private javax.swing.JProgressBar yoyo;
    // End of variables declaration//GEN-END:variables
}
